action_id: trunk-share-with-everyone
date: 2025-01-08 18:55:23
run: trunk config share --notify --allow-daemon-start=false
run_from: ""
trigger: .git/info/exclude
result:
  exit_code: 1
  out: ""
  err: Exception occurred while executing 'trunk-share-with-everyone'. See .trunk\out\LgmRN.yaml for details.
  error_path: C:\Users\user\Documents\New folder\coursework-group_24\.trunk\out\LgmRN.yaml
timestamp: 1736362523
full_timestamp:
  nanos: 429779000
  seconds: 1736362523
trunk_version: 1.22.8
